export enum ActivityType {
  USER_REGISTRATION = 'USER_REGISTRATION',
  MEMO_CREATION = 'MEMO_CREATION',
  MEMO_UPDATE = 'MEMO_UPDATE',
  CALENDAR_MEMO_CREATION = 'CALENDAR_MEMO_CREATION',
  CALENDAR_MEMO_UPDATE = 'CALENDAR_MEMO_UPDATE',
}
