export enum ActivityType {
  USER_REGISTRATION = 'USER_REGISTRATION',
  MEMO_CREATION = 'MEMO_CREATION',
  MEMO_UPDATE = 'MEMO_UPDATE',
  TODO_CREATION = 'TODO_CREATION',
  TODO_UPDATE = 'TODO_UPDATE',
}
